---
# tasks file for vmwaretools/Suse

- name: For SUSE <= 11
  block:
    - name: Get latest vmware package version if not predefined in vmwaretools_repo_version
      ansible.builtin.uri:
        url: "{{ vmwaretools_yum_server }}{{ vmwaretools_yum_path }}/esx/{{ vmwaretools_tools_version }}/repos/index.html"
        return_content: yes
      changed_when: false
      register: vmwaretools_web_page

    - name: Get details about repository package version if vmwaretools_repo_version is undefined
      ansible.builtin.set_fact:
        vmwaretools_repo_version: "{{ vmwaretools_web_page.content | regex_findall('vmware-tools-repo-SLES' + ansible_distribution_version|string + '.(.*).sles' + ansible_distribution_major_version|string + '.' + ansible_architecture + '.rpm') | first | string }}"
  when: vmwaretools_repo_version is undefined and ansible_distribution_major_version|int <= 11

- name: For SUSE == 11
  block:
    - name: Install vmware-tools repository for SLES 11
      community.general.zypper:
        name: "{{ vmwaretools_yum_server }}{{ vmwaretools_yum_path }}/esx/{{ vmwaretools_tools_version }}/repos/vmware-tools-repo-SLES{{ ansible_distribution_version }}-{{ vmwaretools_repo_version }}.sles{{ ansible_distribution_major_version }}.{{ ansible_architecture }}.rpm"
      register: result
      until: result is succeeded

    - name: Remove the open-vm-tools if they are installed not to block vmware-tools installation
      community.general.zypper:
        name: open-vm-tools
        state: absent

    - name: Install vmware-tools
      community.general.zypper:
        name: vmware-tools-esx
        disable_gpg_check: yes
      register: result
      until: result is succeeded
  when: ansible_distribution_major_version|int == 11

- name: Installing Open VMware Tools (open-vm-tools) for SLES12 and higher or OpenSuse
  community.general.zypper:
    name: open-vm-tools
  register: result
  until: result is succeeded
  when: ansible_distribution_major_version|int >= 12
